config/routes.rb
Rails.application.routes.draw do
  get 'import_cat/index'

  resources :cats do
    member do
      get :hide
      get :unhide
    end
  end
  get 'random' => 'cats#random'
  root to: "cats#random"

end

app/models/cat.rb
class Cat < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :set_cat, only: [:show, :edit, :update, :destroy, :hide, :unhide]

  # GET /cats
  # GET /cats.json
  def index
    @cats = Cat.paginate(:page => params[:page], :per_page => 25)
  end

  def hide
    @cat.is_active=0
    @cat.save()
    respond_to do |format|
      format.html { redirect_to @cat, notice: 'Cat was successfully hidden.' }
      format.json { head :no_content }
    end
  end

  def unhide
    @cat.is_active=1
    @cat.save()
    respond_to do |format|
      format.html { redirect_to @cat, notice: 'Cat was successfully shown.' }
      format.json { head :no_content }
    end
  end
  def random
    @cat = Cat.where(:is_active => true).order_by_rand.first
  end
  # GET /cats/1
  # GET /cats/1.json
  def show
  end

  # GET /cats/new
  def new
    @cat = Cat.new
  end

  # GET /cats/1/edit
  def edit
  end

  # POST /cats
  # POST /cats.json
  def create
    @cat = Cat.new(cat_params)

    respond_to do |format|
      if @cat.save
        format.html { redirect_to @cat, notice: 'Cat was successfully created.' }
        format.json { render :show, status: :created, location: @cat }
      else
        format.html { render :new }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cats/1
  # PATCH/PUT /cats/1.json
  def update
    respond_to do |format|
      if @cat.update(cat_params)
        format.html { redirect_to @cat, notice: 'Cat was successfully updated.' }
        format.json { render :show, status: :ok, location: @cat }
      else
        format.html { render :edit }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cats/1
  # DELETE /cats/1.json
  def destroy
    @cat.destroy
    respond_to do |format|
      format.html { redirect_to cats_url, notice: 'Cat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cat
      @cat = Cat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cat_params
      params.require(:cat).permit(:url, :by, :license, :license_image, :by_url, :name,:source_url, :is_active)
    end
end

app/controllers/import_cat_controller.rb
class ImportCatController < ApplicationController
  def index
    require 'open-uri'
    FlickRaw.api_key="038cc084285dc4c37fed1d5936a79cc3"
    FlickRaw.shared_secret="f003890d412f89af"
    url=''
    page=1
    while (page < 100)
      page = page+1
      fliJson=JSON.load(open("https://api.flickr.com/services/rest/?method=flickr.photos.search&api_key=038cc084285dc4c37fed1d5936a79cc3&tags=cats&license=4%2C5%2C6&format=json&nojsoncallback=1&per_page=100&page=#{page}", {ssl_verify_mode: OpenSSL::SSL::VERIFY_NONE}))
      @photos = fliJson["photos"]["photo"]

      @photos.map{ |p|

        photo =  flickr.photos.getInfo :photo_id => p["id"] #, :secret => p["secret"]
        sizes = flickr.photos.getSizes :photo_id => photo.id

        original = sizes.find {|s| s.label == 'Original' }
         if (original && original.width.to_i >  original.height.to_i && original.width.to_i > 1024)
          cat = Cat.new
          cat.by=photo.owner.realname.empty? ? photo.owner.username : photo.owner.realname
          cat.url = original.source
          #cat.url="https://farm#{photo.farm}.staticflickr.com/#{photo.server}/#{photo.id}_#{photo.secret}.jpg"
          cat.license= photo.license
          cat.by_url="https://www.flickr.com/people/#{photo.owner.nsid}"
          cat.name=photo.title

          cat.source_url= photo.urls.find{|u| u.type=='photopage'}._content
            unless Cat.exists?(:source_url=>cat.source_url)
              cat.save()
            end
         end
      }
      @import_cat=JSON.pretty_generate(fliJson)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/import_cat_helper.rb
module ImportCatHelper
end

app/views/cats/_form.html.erb
<%= form_for(@cat) do |f| %>
  <% if @cat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cat.errors.count, "error") %> prohibited this cat from being saved:</h2>

      <ul>
      <% @cat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
    <div class="field">
      <%= f.label :source_url %><br>
      <%= f.text_field :source_url %>
    </div>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
  <div class="field">
    <%= f.label :by %><br>
    <%= f.text_field :by %>
  </div>
    <div class="field">
      <%= f.label :by_url %><br>
      <%= f.text_field :by_url %>
    </div>
  <div class="field">
    <%= f.label :license %><br>
    <%= f.text_field :license %>
  </div>
  <div class="field">
    <%= f.label :license_image %><br>
    <%= f.text_field :license_image %>
  </div>


    <div class="field">
      <%= f.label :is_active %><br>
      <%= f.text_field :is_active %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cats/edit.html.erb
<h1>Editing Cat</h1>

<%= render 'form' %>

<%= link_to 'Show', @cat %> |
<%= link_to 'Back', cats_path %>

app/views/cats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cats</h1>

<table border="1px">
  <thead>
    <tr>
      <th>Url</th>
      <th>By</th>
      <th>License</th>
      <th>License image</th>
      <th>Shown?</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @cats.each do |cat| %>
      <tr>
        <td><a href="<%=url_for cat  %>"> <img width="300px" style="width: 300px" src="<%= cat.url %>" /></a></td>
        <td><%= cat.by %></td>
        <td><%= cat.license %></td>
        <td><%= cat.license_image %></td>
        <td><%= cat.is_active %></td>
        <td><%= link_to 'Hide', hide_cat_path(cat) %></td>
        <td><%= link_to 'unHide', unhide_cat_path(cat) %></td>
        <td><%= link_to 'Edit', edit_cat_path(cat) %></td>
        <td><%= link_to 'Destroy', cat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= will_paginate @cats %>
    <%= link_to 'New Cat', new_cat_path %>

app/views/cats/new.html.erb
<h1>New Cat</h1>

<%= render 'form' %>

<%= link_to 'Back', cats_path %>

app/views/cats/random.html.erb
<p id="notice"><%= notice %></p>
<div class="catdiv" >

<p class="catimg  clear">

  <img style="max-width: 100%; max-height: 100%" src="<%= @cat.url %>"/>

</p>

  <div class="catMeta">
    <p><span class="icon icon-info"></span></p>
<p class="catSource">
  <span class="icon icon-image"></span>

  <strong>Source:</strong>
  <a href="<%= @cat.source_url %>"> <%= @cat.name.empty? ? @cat.source_url : @cat.name %></a>
  <span class="icon icon-flickr3"></span>
</p>


<p class="catBy">
  <strong>
    <span class="icon icon-quill"></span>By:
  </strong>
  <a href="<%= @cat.by_url %>"> <%= @cat.by %></a>
</p>

<p class="catLicense">
  <strong>
    <span class="icon icon-shield"></span></strong>
  License:
  <a href="<%= @cat.license_image %>"><%= @cat.license %></a>
</p>
    <p><span class="icon icon-link"></span> <a href="<%= url_for @cat %>">Link</a></p>
    <p><span class="icon icon-cancel-circle"></span> <a href="<%= hide_cat_path  @cat %>">Hide</a></p>
  </div>

</div>
<div class="clearfix"></div>

app/views/cats/show.html.erb
<p id="notice"><%= notice %></p>
<div class="catdiv" >

  <p class="catimg  clear">

    <img style="max-width: 100%; max-height: 100%" src="<%= @cat.url %>"/>

  </p>

  <div class="catMeta">
    <p><span class="icon icon-info"></span></p>
    <p class="catSource">
      <span class="icon icon-image"></span>

      <strong>Source:</strong>
      <a href="<%= @cat.source_url %>"> <%= @cat.name.empty? ? @cat.source_url : @cat.name %></a>
      <span class="icon icon-flickr3"></span>
    </p>


    <p class="catBy">
      <strong>
        <span class="icon icon-quill"></span>By:
      </strong>
      <a href="<%= @cat.by_url %>"> <%= @cat.by %></a>
    </p>

    <p class="catLicense">
      <strong>
        <span class="icon icon-shield"></span></strong>
      License:
      <a href="<%= @cat.license_image %>"><%= @cat.license %></a>
    </p>
    <p><span class="icon icon-link"></span> <a href="<%= url_for @cat %>">Link</a></p>

    <p><span class="icon icon-cancel-circle"></span> <a href="<%= hide_cat_path  @cat %>">Hide</a></p>
    <p><span class="icon icon-checkmark"></span> <a href="<%= unhide_cat_path  @cat %>">Show</a></p>
  </div>

</div>
<div class="clearfix"></div>


<%= link_to 'Edit', edit_cat_path(@cat) %> |
<%= link_to 'Back', cats_path %>

app/views/import_cat/index.html.erb
<h1>ImportCat#index</h1>
<p>Find me in app/views/import_cat/index.html.erb</p>
<pre>
<%= @import_cat %>
    </pre>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Random Cat</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
              m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-57894897-1', 'auto');
      ga('send', 'pageview');

  </script>
</head>
<body>

<%= yield %>

</body>
</html>